# Basic Shiz

##123


In [3]:
x=4
y=3
x+y
##123

7

In [4]:
#func
def add(x,y):
    return x+y
add(5,15)

20

In [5]:
def add(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z
print(add(1,2))
a=add(1,2,3)
print(a)

3
6


In [6]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ') #[0] selects the first elenmente list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

['Christopher', 'Arthur', 'Hansen', 'Brooks']
Brooks


In [2]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}


In [3]:
x['Bill Gates']

'billg@microsoft.com'

In [4]:
for n in x:
    print(n)

Christopher Brooks
Bill Gates


In [5]:
for n in x.items():
    print(n)

('Christopher Brooks', 'brooksch@umich.edu')
('Bill Gates', 'billg@microsoft.com')


In [5]:
for n in x.items():
    print(n)

('Christopher Brooks', 'brooksch@umich.edu')
('Bill Gates', 'billg@microsoft.com')


In [6]:
type('1')

str

In [8]:
x=[1,2,3]
print(x)
print(type(x))

[1, 2, 3]
<class 'list'>


In [9]:
if 1 in[1,2,3]:
    print("smd")
else:
    print('smdfb')
    

smd


In [10]:
a=[1]

In [11]:
a*3

[1, 1, 1]

In [12]:
a.append(3)

In [13]:
a

[1, 3]

In [18]:
a+[1,7]

[1, 3, 1, 7, 1, 7]

In [1]:
func=lambda a,b,c:a+b+c
func(1,2,3)

6

In [2]:
l=[]
for i in range(0,100):
    if(i%2==0):
        l.append(i)
    else:
        continue
l

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [3]:
l=[i for i in range(1,100) if i%2==0]
l

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [5]:
s=[1,4,8,90]
q=[2,2,6,890]
m=map(max,s,q)
for i in m:
    print (i)

2
4
8
890


In [6]:
import numpy as np
import math

In [10]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
a.ndim

2

In [16]:
a.dtype.name

'int32'

In [14]:
len(a)

2

In [15]:
a.shape

(2, 3)

In [20]:
d=np.ones((2,8))
d

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.random.rand(2,3)

array([[0.99326976, 0.12017632, 0.60353571],
       [0.7423486 , 0.41767731, 0.31939185]])

In [30]:
f=np.arange(1,101,5)
f

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [32]:
a=np.array([[1,2],[2,3]])
b=np.array([[7,0],[1,13]])
c=a-b
c

array([[ -6,   2],
       [  1, -10]])

In [33]:
c=a/b
c

C:\Users\Rohan\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.14285714,        inf],
       [2.        , 0.23076923]])

In [35]:
c=a*b
c

array([[ 7,  0],
       [ 2, 39]])

In [36]:
c=a@b
c

array([[ 9, 26],
       [17, 39]])

In [37]:
c>10
c

array([[ 9, 26],
       [17, 39]])

In [38]:
c>10

array([[False,  True],
       [ True,  True]])

In [39]:
c%2==0

array([[False,  True],
       [False, False]])

In [40]:
c.sum()

91

In [41]:
c.max()

39

In [42]:
c.mean()

22.75

In [45]:
f=np.arange(1,11,1).reshape(2,5)
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
a=np.array([[1,2,3],[4,5,6]])

In [47]:
a[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [48]:
a[1]

array([4, 5, 6])

In [49]:
a[1][2]

6

In [50]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a[1:1]

array([], shape=(0, 3), dtype=int32)

In [52]:
a>3

array([[False, False, False],
       [ True,  True,  True]])

In [53]:
a[1][2]>3

True

In [54]:
a[:1,2:3]

array([[3]])

In [55]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a[0,0]=a[:1,2:3]
a

array([[3, 2, 3],
       [4, 5, 6]])

In [57]:
a

array([[3, 2, 3],
       [4, 5, 6]])

In [58]:
a>10

array([[False, False, False],
       [False, False, False]])

In [59]:
import re

In [63]:
text="GODI AM A GOD"
if (re.match("GOD",text)):
    print("lit")
else:
     print("litsmd")

lit


In [67]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."
re.findall("Amy ",text)

['Amy ', 'Amy ', 'Amy ']

In [77]:
grades="ACAAAABCBCBAA"
re.findall("AA",grades)

['AA', 'AA', 'AA']

In [78]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [79]:
a=np.ones((2,8))

In [80]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [81]:
a=np.random.rand(2,2)
a

array([[0.28058133, 0.22470708],
       [0.49274245, 0.00375982]])

In [82]:
a=np.random.rand(20,20)
b=np.random.rand(20,20)
print(a)
print(b)

[[6.51938532e-01 3.09991977e-02 4.78871990e-01 3.90182713e-01
  9.59958496e-01 5.86531481e-01 8.42109018e-02 3.64311293e-01
  8.91649547e-01 4.29278984e-01 4.29672534e-01 6.14414549e-02
  7.34583888e-01 4.99620429e-01 4.75669919e-02 6.64079890e-01
  7.41486972e-01 9.39588734e-01 6.05626540e-01 8.08129711e-01]
 [4.81344319e-02 7.58597586e-01 4.98615618e-01 6.81428173e-01
  2.64985550e-01 6.10219406e-01 4.66529234e-01 2.66265402e-01
  8.01058972e-01 1.93068667e-01 2.90479882e-01 9.21523225e-01
  5.19159927e-01 5.26142561e-01 8.43391242e-01 7.15297207e-01
  6.99850226e-01 1.27815858e-01 4.05657252e-01 1.77924492e-01]
 [5.25559903e-01 4.03891482e-02 9.53204841e-01 5.20615347e-01
  9.33202142e-01 7.19209345e-01 2.67356837e-01 7.87449710e-01
  7.03696485e-01 5.19533059e-01 5.52205806e-01 1.02838248e-01
  2.69896789e-01 7.77865688e-01 7.81346559e-01 8.27165565e-01
  1.12209287e-01 6.53726113e-01 2.68542013e-02 3.73524701e-01]
 [1.28519327e-01 5.84218334e-01 4.69415258e-01 3.45705139e-01
  6.1

In [96]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result
l2_dist(a.T,b.T)

7.65853652892395

In [97]:
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)

In [98]:
a3.shape

(1, 4)

In [99]:
a4.shape

(3,)

In [100]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)

In [101]:
a1.shape

(4,)

In [102]:
a2.shape

(4, 1)

In [103]:
a5 = np.linspace(1 ,4, 4)
a5.shape

(4,)

In [104]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)





[[0 0 1]
 [1 1 1]]


In [106]:
import re
s = 'ACBCAC'
re.findall("^[AC]",s)

['A']

In [109]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

L



5

In [112]:
s='''Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'''

In [113]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

In [118]:
import re

pattern = '[]'
print((re.findall(pattern,s)))





['O', 'f', 'f', 'i', 'c', 'e', ' ', 'o', 'f', ' ', 'R', 'e', 's', 'e', 'a', 'r', 'c', 'h', ' ', 'A', 'd', 'm', 'i', 'n', 'i', 's', 't', 'r', 'a', 't', 'i', 'o', 'n', ':', ' ', '(', '7', '3', '4', ')', ' ', '6', '4', '7', '-', '6', '3', '3', '3', ' ', '|', ' ', '4', '3', '2', '5', ' ', 'N', 'o', 'r', 't', 'h', ' ', 'Q', 'u', 'a', 'd', 'O', 'f', 'f', 'i', 'c', 'e', ' ', 'o', 'f', ' ', 'B', 'u', 'd', 'g', 'e', 't', ' ', 'a', 'n', 'd', ' ', 'F', 'i', 'n', 'a', 'n', 'c', 'i', 'a', 'l', ' ', 'A', 'd', 'm', 'i', 'n', 'i', 's', 't', 'r', 'a', 't', 'i', 'o', 'n', ':', ' ', '(', '7', '3', '4', ')', ' ', '6', '4', '7', '-', '8', '0', '4', '4', ' ', '|', ' ', '3', '0', '9', ' ', 'M', 'a', 'y', 'n', 'a', 'r', 'd', ',', ' ', 'S', 'u', 'i', 't', 'e', ' ', '2', '0', '5', 'H', 'e', 'a', 'l', 't', 'h', ' ', 'I', 'n', 'f', 'o', 'r', 'm', 'a', 't', 'i', 'c', 's', ' ', 'P', 'r', 'o', 'g', 'r', 'a', 'm', ':', ' ', '(', '7', '3', '4', ')', ' ', '7', '6', '3', '-', '2', '2', '8', '5', ' ', '|', ' ', '3', '3',